#!/bin/bash
set -e

if [ ! -f .env.cloud ]; then
  echo "No existe .env.cloud"
  exit 1
fi

source .env.cloud
trap 'rm -f .env.production' EXIT

required_vars=(
  AUTH_SERVICE_URL
  CONFIGURACION_GENERAL_API_URL
  NEXT_PUBLIC_API_GATEWAY_URL
  NEXT_PUBLIC_ACTIVOS_API_URL
  NEXT_PUBLIC_COMBUSTIBLE_API_URL
  NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL
  NODE_ENV
)

for var_name in "${required_vars[@]}"; do
  if [ -z "${!var_name}" ]; then
    echo "Falta configurar ${var_name} en .env.cloud"
    exit 1
  fi
done

# CONFIGURACION_GENERAL_API_URL es server-only (la usa el Route Handler), por
# eso va solo en runtime (VARS) y no en BUILD_VARS.
VARS="AUTH_SERVICE_URL=${AUTH_SERVICE_URL},CONFIGURACION_GENERAL_API_URL=${CONFIGURACION_GENERAL_API_URL},NEXT_PUBLIC_API_GATEWAY_URL=${NEXT_PUBLIC_API_GATEWAY_URL},NEXT_PUBLIC_ACTIVOS_API_URL=${NEXT_PUBLIC_ACTIVOS_API_URL},NEXT_PUBLIC_COMBUSTIBLE_API_URL=${NEXT_PUBLIC_COMBUSTIBLE_API_URL},NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL=${NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL},NODE_ENV=${NODE_ENV}"

BUILD_VARS="NEXT_PUBLIC_API_GATEWAY_URL=${NEXT_PUBLIC_API_GATEWAY_URL},NEXT_PUBLIC_ACTIVOS_API_URL=${NEXT_PUBLIC_ACTIVOS_API_URL},NEXT_PUBLIC_COMBUSTIBLE_API_URL=${NEXT_PUBLIC_COMBUSTIBLE_API_URL},NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL=${NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL},NODE_ENV=${NODE_ENV}"

cat > .env.production <<EOF
NEXT_PUBLIC_API_GATEWAY_URL=${NEXT_PUBLIC_API_GATEWAY_URL}
NEXT_PUBLIC_ACTIVOS_API_URL=${NEXT_PUBLIC_ACTIVOS_API_URL}
NEXT_PUBLIC_COMBUSTIBLE_API_URL=${NEXT_PUBLIC_COMBUSTIBLE_API_URL}
NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL=${NEXT_PUBLIC_SOCIO_NEGOCIOS_API_URL}
EOF

gcloud run deploy front-ddd \
  --source . \
  --region=us-central1 \
  --clear-base-image \
  --set-build-env-vars="${BUILD_VARS}" \
  --set-env-vars="${VARS}"

  